### ISSUE TITLE
How show Xiaomi temperature&humidity sensor data in homekit?

### ISSUE THREAD

**Issue by EugeneLiu** [custom-components/sensor.mitemp_bt#112]
my homkit config is 
```
homekit:
- filter:
    include_domains:
      - sensor
      - fan
      - light
      - climate
    include_entities:
      - sensor.mi_t_a4c138cdda7b
      - sensor.mi_h_a4c138cdda7b
```

but temperature&humidity sensor data not show my homekit.
