### ISSUE TITLE
Humidity Reporting Fine, Temperature "Unknown" on LYWSD03MMC (ATC_MiThermometer)

### ISSUE THREAD

**Issue by anndrewww** [custom-components/sensor.mitemp_bt#132]
Two (2) LYWSD03MMC devices flashed with the ATC_MiThermometer .bin.

Both are reporting Humidity with no issues but Temperature on both is reporting as "Unknown".

Both have the following settings via the Web Flasher:

> Smiley: Off 
> 
> Advertising Type:  Mi Like
> 
> Sensor display: In °F
> 
> Show battery in LCD: Disabled
> 
> Advertising interval: 1 Minute

My Mi_Temp.yaml is:

> platform: mitemp_bt
>     rounding: True
>     decimals: 1
>     period: 60
>     log_spikes: False
>     use_median: False
>     active_scan: False
>     hci_interface: 0
>     batt_entities: False

**Comment by Ernst79** [comment]
My first guess, perhaps changing the sensor display to Fahrenheit also changes the ble messages to Fahrenheit.  

20 degrees Celsius will become 68 degrees Fahrenheit, which is outside the range as set in const.py. Could you try to change the following two lines in const.py to appropriate values in Fahrenheit?

CONF_TMIN = -40.0
CONF_TMAX = 60.0

Please restart HA afterwards and report back your findings.

**Comment by anndrewww** [comment]
I changed the display back to Celsius and the values started to report and convert to Fahrenheit for display into HA. 

If I edit Const.py, values start reporting to HA but are nearly doubled because it's treating them as Celisus and applying the conversion.

**Comment by zanchin** [comment]
Same observations here. When I set the display to Fahrenheit and change const.py, I see correct entity attributes:

```yaml
last packet id: 116
rssi: -66
sensor type: LYWSD03MMC
mac address: 'A4:C1:38:B8:30:2D'
battery_level: 85
last mean of: 4
median: 74.6
mean: 74.6
unit_of_measurement: °F
friendly_name: mi temperature A4C138B8302D
device_class: temperature
```

However, when graphed, HA interprets it as a Celsius temperature and multiplies the value (the jump is when I switched from C to F):
![image](https://user-images.githubusercontent.com/281978/97323343-1771a300-1847-11eb-925d-c6ba0afec808.png)

Note than when display was set to C, HA was graphing temperature with the F value, but with the °C unit, which means it can't be graphed next to other °F sensors.

Is this controllable from within the integration, or is it a setting in HA?
