### ISSUE TITLE
batt_entities invalid configuration

### ISSUE THREAD

**Issue by peetereczek** [custom-components/sensor.mitemp_bt#36]
I have the latest update installed

![image](https://user-images.githubusercontent.com/42431204/74535733-c333c680-4f36-11ea-99f9-e9f79bd41c4b.png)

But can't use batt_entities feature
![image](https://user-images.githubusercontent.com/42431204/74535801-e65e7600-4f36-11ea-8e98-e8f96decd45b.png)

My configuration:
```yaml
  - platform: mitemp_bt
    rounding: True
    decimals: 1
    period: 60
    log_spikes: False
    use_median: False
    active_scan: False
    hci_interface: 0
    batt_entities: True
```

How can I fix that?
