### ISSUE TITLE
No battery information

### ISSUE THREAD

**Issue by eliobou** [custom-components/sensor.mitemp_bt#5]
Hello, I succesfully installed the custom component and it's working great except I don't have the battery sensor. I don't find it in the entity list. Is it a bug or something I miss ?

**Comment by Ernst79** [comment]
It's not a sensor, it's an attribute of the temperature and humidity sensor (see battery_level at the bottom). 

![image](https://user-images.githubusercontent.com/24375847/69708946-ccae4f00-10fc-11ea-9ebe-2a2ae4663631.png)

You can use a template sensor if you want this displayed as a sensor in Home Assistant

https://www.home-assistant.io/integrations/template/

**Comment by Magalex2x14** [comment]
@Ernst79, how long have you been using the sensor in your screenshot? I collect statistics on battery consumption, but my sensors are now only 3 months old (85% of the charge on average). At the beginning there were experiments, and not all these 3 months used a passive scanning mode. But while it turns out about 5% per month approximately.

**Comment by Ernst79** [comment]
Mine is of 11 months old now, but I started with the original home assistant component in the beginning. Not sure when I changed to your custom_component.

**Comment by eliobou** [comment]
Thanks for you answer. My config if someone don't know how to do it : 
`- platform: template
    sensors:
      mi_b_582d3435cfeb:
        friendly_name: "Niveau de batterie"
        unit_of_measurement: "%"
        value_template: "{{ state_attr('sensor.mi_t_582d3435cfeb', 'battery_level') }}"`

**Comment by Ernst79** [comment]
You mixed the first to lines. Try this:

```
sensor:
  - platform: template
     mi_b_582d3435cfeb:
       friendly_name: "Niveau de batterie"
       unit_of_measurement: "%"
       value_template: "{{ state_attr('sensor.mi_t_582d3435cfeb', 'battery_level') }}"
```

**Comment by ma-zal** [comment]
Do not forget to `device_class`. Correct config is:
```
sensor:
  - platform: template
    sensors:
      mi_b_582d34339449:
        friendly_name: "Baterie"
        unit_of_measurement: "%"
        value_template: "{{ state_attr('sensor.mi_t_582d34339449', 'battery_level') }}"
        device_class: "battery"
```
