### ISSUE TITLE
Decimals

### ISSUE THREAD

**Issue by oneseventhree** [custom-components/sensor.mitemp_bt#58]
In const.py can this be the default on future releases:

DEFAULT_DECIMALS = 1

I don't know why anyone would want 2 decimals but I keep having to change it back each update.

Thank you in advance :)

**Comment by Ernst79** [comment]
You can always set rounding to true and decimals to 1 in your config. That should not change on updating the component.

```
sensor:
  - platform: mitemp_bt
    rounding: True
    decimals: 1
```
