### ISSUE TITLE
Detect missing or faulty bluetooth connection

### ISSUE THREAD

**Issue by clau-bucur** [custom-components/sensor.mitemp_bt#65]
Is there a way to detect, in HA, if the component is unable to read data from bluetooth?

From what I see now, there is no indication that the bluetooth connection is broken (either the dondle is removed, drivers crashed, whatever).
I run HassIO in a VirtualBox VM from a Windows host, so the bluetooth device can, from time to time, become unavailable to VM.

**Comment by Magalex2x14** [comment]
All entities created by our component have the `force_update` property set, therefore, it seems to me that a reliable enough solution is to use the `last_updated` attribute.
For example, like this:
```yaml
binary_sensor:
  - platform: template
    sensors:
      bt_stuck:
        friendly_name: "BT"
        value_template: >-
          {% set btvalues = [
            states.sensor.mi_t_1.last_updated,
            states.sensor.mi_t_2.last_updated,
            states.sensor.mi_h_1.last_updated,
            states.sensor.mi_h_2.last_updated]%}
          {{ (as_timestamp(now())-as_timestamp(btvalues | max)) > 120 }}
        device_class: problem
        icon_template: >-
          {% if is_state("binary_sensor.bt_stuck", "on") %}
            mdi:bluetooth-off
          {% else %}
            mdi:bluetooth
          {% endif %}
```
However, there are still options - use the [command line sensor](https://www.home-assistant.io/integrations/sensor.command_line/) in combination with a bash script (which starts and parses the output of the `hciconfig` command, for example). But I don’t have such a ready-made solution.

**Comment by clau-bucur** [comment]
Thanks Alex! That binary sensor is exactly what I'm looking for.
I'm testing it now, however it's never changing to state ON.

If I run the value_template in the Developer Tool / Template section, it returns "True" and "False" as expected,
I might be missing something, I'll keep on investigating.

**Comment by clau-bucur** [comment]
Looks like the sensor is not being automatically updated.
I added `entity_id: sensor.time` to the `bt_stuck` sensor and enabled time sensor component in my configuration.yaml:
```yaml
sensor:
  - platform: time_date
    display_options:
      - time
```
The sensor changes state now, after two minutes of faulty bluetooth communication.

**Comment by Magalex2x14** [comment]
Yes, I forgot about this feature of the operation of template sensors. The `time_date` platform was already included in my config. I suspect that this is enough, and adding `entity_id: sensor.time` to the binary sensor code is not necessary (but this will not hurt).
I think this is worthy of inclusion in the [FAQ](https://github.com/custom-components/sensor.mitemp_bt/blob/master/faq.md).

Summary yaml:
```yaml
sensor:
  - platform: time_date
    display_options:
      - time

binary_sensor:
  - platform: template
    sensors:
      bt_stuck:
        friendly_name: "BT"
        value_template: >-
          {% set btvalues = [
            states.sensor.mi_t_1.last_updated,
            states.sensor.mi_t_2.last_updated,
            states.sensor.mi_h_1.last_updated,
            states.sensor.mi_h_2.last_updated]%}
          {{ (as_timestamp(now())-as_timestamp(btvalues | max)) > 120 }}
        device_class: problem
        entity_id: sensor.time
        icon_template: >-
          {% if is_state("binary_sensor.bt_stuck", "on") %}
            mdi:bluetooth-off
          {% else %}
            mdi:bluetooth
          {% endif %}
```
where `sensor.mi_t_1` and others are all sensors whose `last_updated` time is checked, and `binary_sensor.bt_stuck` will turn on if more than 120 seconds have passed since the last update of the "youngest" one.
